# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vjiAT7/GQU0p28On54lNZ9xrw0j+pKvzXyFpwh2vVPgJvjgNQEHClhiX8mPC14y57tgkFJsWG34FSDvqGb7AnelycAIF5cjkA4CRXckHR/HqB6cR8ysz+AYPQxMSU+pGUNwFOczn2TdB8oIQ31tPU/+4HNoUjlz8ccevXDtypj20sNkUZWemZOQkKy29JYClBVsT8WxHOXuJ/O5C1UDDWWP3uv4JQ4U8SXBmHuj1vizvqFIwqQ==,iv:R9mNTmHZOwxyNm0gThB+AJUXinws3x/o1AANWNf/Fnk=,tag:0yZ2Y9dyeA4N3I6vdmlQSg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pfedspsf3qlym9spsfqsxpwcu5d393aeyxf3cwaxurjax6dqrccs03mf04
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUm1PcHBZOUViTzJkc1F3
        YnowQWRXbUtDakZOTURNWDRlQUVzZGkyWUVBCjhCc0VrMUNRd0JOTkJvTG5NU3oz
        eHRHVktTYjNJdzlJVHFnUkY4MnU0elkKLS0tIGFBbFkzSi9Jc2dlUkxNVmVMS3hj
        NEVud2UwbVc1c0RHNmlSVGFiYVBTR0kKUsVf8iVzsVQGNiqn/i1icuM+gwEaBBDe
        FT946wsy5Et+5ukX7i2gU3alIuoR7cU2KrIu89LORrT2RCQ2QX3DYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-18T15:50:36Z"
  mac: ENC[AES256_GCM,data:n0FOwJHzLzVphkOVy8nphbdmmOZUzI/BbihbmtsD/WajyWn79bUDStwiYV8xf7ZSo0FZ592BKnxTgo/4ygJnRkjCsVucl9U9huuC7HkfNWqQVyfSInBIRsOUZxB2198mVledT/X98QbTueMLOtzaxOK9dVgue8i6aeTt4hwjJfY=,iv:nuKltjPGpawO19JxZHjsqdoZA8qSjfnm71Mr+j1se1A=,tag:sm+wjAh2td18ud1YfJk5rA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
