# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vRw9vJKRBKcdvq7Cn7/P1J6UtI5mCe18Dm1/qrgvML8=,iv:dN+y5fpZYG9XrM5GZdsfd/6jSXEFQIkYXNp/T5Uurzo=,tag:yXAZxV03DNMX4XElaNjZVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pfedspsf3qlym9spsfqsxpwcu5d393aeyxf3cwaxurjax6dqrccs03mf04
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbVRQOHAxRzFucWtHd2Ft
        aktQMStJSEZqYzEyc0xzUGNpZmxsa1NacUhRCkk5cWpyUjU5Sk9lMXdVL1haTHRC
        MlhwajlXcmpReWhHcmV6WU03QmFYZjAKLS0tIEtWUndSUnlmRFBHRThtMTdvZDNw
        ekxKL0o0YVROZkZzQjhTVHhuSit5QkkKTMMRB/29MPNUy+igy65eU7vyqutJmLE2
        yFAuLEGIFTGRzVz75nwlT5YsHGilSUeQi9ns6gCMCwAJoq9nbcwdRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-18T15:50:36Z"
  mac: ENC[AES256_GCM,data:10UmFoNm1odZf43c85ZCDD9wViYF11XJRTfJazprJucdUApoVxhQMHhguCu0/Lw5yAEDYPT0RdMFpGvBFM/q3z0WMVNEwqMNqa3A/WdFqi8vpDYwCjLWWRD0H/CIXesTsCn6xSdQPPlkmOWI/l913Bn18Vo0pmOfFkmPAM22uuQ=,iv:RbA08/C3NXeCCjwyudcRedH6HdRFIZS+XCT28NLrAe0=,tag:qp0j/0wC8S/CO3wVpWTkqw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
