apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uxLoJFdu4j5YIkY=,iv:RCLz/TBQnlvQhnIf5k6uzo7Z907nl7iynijqdgYPUjI=,tag:ZMUcxAORHf+pzDLNQklfHg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pfedspsf3qlym9spsfqsxpwcu5d393aeyxf3cwaxurjax6dqrccs03mf04
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRFNRa3A0cHdNWnJQT3hY
        WnN3ZUFzQ3VCZ01nY0tnVFZnNTU4L0lZN3ljCjZzMEtYUkZsL0xXK0tNWE96NFN5
        Z08xczNrQ2xwRkJkQkNZb0JmdlFxUE0KLS0tIDdMZ0NMQ3pYd3VaeEJCRHpocjNy
        UnROVWRFMTBoUWFibitOSUNBTFhBUmcKLDrmd/9UfQg4086LJ6xbbpCFnKB1MD3q
        J8XaAYnUuSG2pPXGCPMTpo2tCJKu5Cfww+n+XQ85xM2kWIlkv8PkXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-18T15:50:36Z"
  mac: ENC[AES256_GCM,data:EGGOOQax6Vd5dSZ9swdptr4zVdnuGgVI91gsxcEx4kegCq3RpL9czpH/9tbB9/2kzYfCBUkHy/uj5SNkR+SXCbC0klXekXYPmJrri0hDVEBcOx4T90KBFCM52ZBTPghaJjkhKQxy/qO9Tq3bdbZVLJ5yzJmi9WcKqiFWQQOv6kk=,iv:DOzro1jYNB6K7rcwNiXAdpxH7orHKtsKCRJrGd2e+7s=,tag:wcKpGPl3Zso0hBFnmYIqpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
